name: ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: formatting and testing
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check for errors
        run: go vet ./... && staticcheck ./...

      - name: Run tests
        run: go test ./...

